contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dmsqc channel"
    url: https://nfcore.slack.com/channels/dmsqc
    about: Discussion about the nf-core/dmsqc pipeline
